### ISSUE TITLE
Very RAM-eating program

### ISSUE THREAD

**Issue by AlshaKrut9523-2** [AceLewis/my_first_calculator.py#142]
My Mem Reduct showed me 90% used RAM in a couple of seconds. I think that the RAM is filled up because the code does not process numbers by Python itself, and there are already a lot of ready-made answers to mathematical questions.
Rewrite your code

**Comment by AceLewis** [comment]
To be clear, this repo is literally a joke. The code is supposed to be bad, this is not how you would create a calculator.

The [README.md](https://github.com/AceLewis/my_first_calculator.py/blob/master/README.md) explains why I made the joke, and the generator ([generator.py](https://github.com/AceLewis/my_first_calculator.py/blob/master/generator.py)) that made [my_first_calculator.py](https://github.com/AceLewis/my_first_calculator.py/blob/master/my_first_calculator.py) is in the repo.
