### ISSUE TITLE
I put 2 + 1 and the output was 21

### ISSUE THREAD

**Issue by NikV2** [AceLewis/my_first_calculator.py#154]
How to fix

**Comment by AceLewis** [comment]
https://github.com/AceLewis/my_first_calculator.py/blob/a7aabeaf4973e1c2e5a449ce8bd7e7ee5e091c71/my_first_calculator.py#L219-L220

**Comment by NikV2** [comment]
Scam, i demand a refund otherwise i chargeback.

**Comment by Brandons404** [comment]
> Scam, i demand a refund otherwise i chargeback.

Did you type "2 + 1" in the first input? because they are all supposed to be separate. The python script probably read your input and literally added the two strings "2" and "1", and hitting enter on the other two would default to 0. so you were just using it wrong..

**Comment by NikV2** [comment]
I am obviously messing around. I don't even know what the script does.
