### ISSUE TITLE
5/11 calculated wrong

### ISSUE THREAD

**Issue by 0x17de** [AceLewis/my_first_calculator.py#3]
if num1 == 5 and sign == '/' and num2 == 11:
    print("5/11 = 0.45454545454545453")

5/11 shouldn't have 3 as its last digit.
Rather end with a 5. Also precision seems to vary. ;)

**Comment by JuanPotato** [comment]
#5 should fix this

**Comment by rudrathegreat** [comment]
Another option is to consider NumPy. It is much more accurate and faster than the original Python operations.
