### ISSUE TITLE
Can we add support for 51?

### ISSUE THREAD

**Issue by Drigax** [AceLewis/my_first_calculator.py#46]
I really want to use this calculator but I need 51 support

**Comment by gowrizrh** [comment]
If no one adds, I will make a new fork that adds support for 51.

**Comment by thanadolps** [comment]
[generator.py](..//blob/master/generator.py) can be use to "customize" [my_first_calculator.py](..//blob/master/my_first_calculator.py) to add support for 51

**Comment by cknost** [comment]
> [generator.py](..//blob/master/generator.py) can be use to "customize" [my_first_calculator.py](..//blob/master/my_first_calculator.py) to add support for 51

That's too simple.

**Comment by SwapnilSoni1999** [comment]
calling FBI

**Comment by pablodz** [comment]
up

**Comment by andriivitiv** [comment]
It was very difficult but I did. https://github.com/AceLewis/my_first_calculator.py/pull/62

**Comment by Drigax** [comment]
Ah I see. I think the generator will work for me. Hopefully we can add a dynamic programming type solution to support higher values without needing to generate source.
