### ISSUE TITLE
Human stupidity has no limits. "Programmers" included.

### ISSUE THREAD

**Issue by marciopmm** [AceLewis/my_first_calculator.py#50]

**Comment by REVENGE977** [comment]
True :/ ..

**Comment by HideLord** [comment]
I hope you guys are being satirical because this whole thing is a joke repository. At least read the "Read me"

**Comment by cr4shcod3** [comment]
@HideLord TRUE

**Comment by ziyigogogo** [comment]
Yes, stupidity has no limits. Especially open an issue without reading readme.
Please go read it and then answer my following question:
who is stupid now?
