### ISSUE TITLE
😃

### ISSUE THREAD

**Issue by REVENGE977** [AceLewis/my_first_calculator.py#53]
😇

**Comment by GuilhermeCaeiro** [comment]
Offenses aren't cool, my friend. And the code here is a meme.

**Comment by DrOreo002** [comment]
Chill mate

**Comment by wisn** [comment]
Chill, dude. Please read the README first.

**Comment by cheetosysst** [comment]
Read README

**Comment by cr4shcod3** [comment]
Never thought people would be this serious.

**Comment by ziyigogogo** [comment]
Yes, stupidity has no limits. Especially open an issue without reading readme.
Please go read it and then answer my following question:
who is stupid now?

**Comment by REVENGE977** [comment]
Sure its you and the owner of this repo , 
why do he needs to do fucking 10000 line ?

**Comment by salafm** [comment]
> Sure its you and the owner of this repo ,
> why do he needs to do fucking 10000 line ?

He use a generator.py mate, can u read the code?

**Comment by ziyigogogo** [comment]
> Sure its you and the owner of this repo ,
> why do he needs to do fucking 10000 line ?

Okay, looks like most emojis stand by my side. But don't worry buddy. 
Truth is in the hands of a few people which means you are the blessed one, the one of a kind genius!
Hold your faith and you will be the best programmer ever in the history!
I will be you biggest fan then!

**Comment by REVENGE977** [comment]
i just realized that this is the most cringy thing i've ever done so ..
