### ISSUE TITLE
😇

### ISSUE THREAD

**Issue by REVENGE977** [AceLewis/my_first_calculator.py#54]
😄

**Comment by REVENGE977** [comment]
i mean 100

**Comment by GuilhermeCaeiro** [comment]
850 stars and 101 forks now. :)

**Comment by MiKueen** [comment]
OOF seems like all the memers started using github

**Comment by poteminr** [comment]
@MiKueen  I use this instead of default calculator

**Comment by maharshi-b** [comment]
Its me who posted in r/ProgrammerHumour yesterday

**Comment by Th3OnlyN00b** [comment]
Can we please close this issue as this id not a discussion forum

**Comment by joulev** [comment]
@Th3OnlyN00b I suggest against it because this repository is not a normal repository, there is no reason that an issue in it has to be normal

**Comment by appsdevpk** [comment]
everyone who starred or forked this is a retard

**Comment by appsdevpk** [comment]
no one here have the courage to face the truth

**Comment by joulev** [comment]
@appsdevpk [r/wooosh](https://www.urbandictionary.com/define.php?term=R%2F%20woooosh)

**Comment by Leisffe** [comment]
oof

**Comment by REVENGE977** [comment]
i just realized that this is the most cringy thing i've ever done so ..

**Comment by HashtagAssist** [comment]
> i just realized that this is the most cringy thing i've ever done so ..

but nice that you own the same github account in 2021 XD
