### ISSUE TITLE
This is a fucking joke

### ISSUE THREAD

**Issue by Cyberlytical** [AceLewis/my_first_calculator.py#97]

**Comment by andriivitiv** [comment]
no

**Comment by Cyberlytical** [comment]
yes, it is the least efficient python calculator I have ever seen.

**Comment by aftery142** [comment]
> 
> 
> yes, it is the least efficient python calculator I have ever seen.

splish splash your opinion is trash

**Comment by Cyberlytical** [comment]
You could, I could, we all could create something way better than that piece of shit.

**Comment by Leisffe** [comment]
It's the best one you could ever do.

**Comment by Cyberlytical** [comment]
How about you get back to your UX/UI Designing @Leisffe, know your place.

**Comment by Cyberlytical** [comment]
I don't understand why you support this shit.

**Comment by Leisffe** [comment]
> 
> 
> How about you get back to your UX/UI Designing @Leisffe, know your place.


Lul, imagine being a salty kid waging wars on the internet because of not being able to communicate properly with other human beings irl.

**Comment by Cyberlytical** [comment]
How am I waging wars here? I was stating from the start that this program is clearly a joke and that pretty much all the issues here were non-serious.

It baffles me how many stars this program has for such an un-efficient piece of code that people somehow support.

**Comment by Leisffe** [comment]
>How am I waging wars here?

You've answered your own questions by being a rude piece of junk and still commenting on this clearly troll/joke repo while being just a literally 16 yo kid who still lives with his parents according to your own website. If that repo is your world's biggest problem then it literally tells the story about how important you are irl.
Get yo shit together before trash talking other people for no reason, since you're probably still not earning more money than a guy at the lemonade booth. The fact that I actually have got time to do my main job while just doing my hobbies is self-explanotary, but I guess I'm in the wrong for assuming that 16 year old kid would be intelligent enough to calm his ego down to the true ground.

**Comment by aftery142** [comment]
Guys please do not be rude my mother uses this calculate and she does not like bad people so please refrain from being rude thank you

**Comment by Cyberlytical** [comment]
@Leisffe 

A. What website?
B. If we are bringing age into this, I'm gonna guess you are around 20 ish, living off a crappy £5/hour, part time job in a manky flat, eating ramen and watching daytime TV when you are not at School or Work.
C. Send me an email and I'll respond to it with my passport and driver's license, clearly stating that I'm not 16 and living at home, that website is outdated as fuck. 
D. I really couldn't give 2 fucks about what you think of me, I come to github to collaborate and host projects, not to look at a fucking calculator that would crash your cheap PC that you are on right now.

PS. @aftery142 Send your mother my deepest condolences, I'm sorry that she has had to see this thread, some dumb fucks clearly feel a bit too passionate about this repository.

**Comment by MatteoRaso** [comment]
> @Leisffe
> 
> A. What website?
> B. If we are bringing age into this, I'm gonna guess you are around 20 ish, living off a crappy £5/hour, part time job in a manky flat, eating ramen and watching daytime TV when you are not at School or Work.
> C. Send me an email and I'll respond to it with my passport and driver's license, clearly stating that I'm not 16 and living at home, that website is outdated as fuck.
> D. I really couldn't give 2 fucks about what you think of me, I come to github to collaborate and host projects, not to look at a fucking calculator that would crash your cheap PC that you are on right now.
> 
> PS. @aftery142 Send your mother my deepest condolences, I'm sorry that she has had to see this thread, some dumb fucks clearly feel a bit too passionate about this repository.

If this repo angers you so much, then why are you even here? Just click off.

**Comment by Cyberlytical** [comment]
Consider this a public service - I'm saving you from having to look at this shit by directing your attention to this thread instead.

**Comment by simonpeterdebbarma** [comment]
@Computer-Man497 

You said it yourself, you self aware wolf. This repo is a joke. It's literally a joke. Did you even look around?

**Comment by mattgualdarrama** [comment]
Jesus Christ imagine being this bad at taking a joke.

**Comment by i-mw** [comment]
This boy makes it much funnier .. as if he is part of the show

**Comment by Cyberlytical** [comment]
What if I am part of the joke
